---
title: "Enhancing Access to Alzheimer's Clinical Research Data via R Packages: the Alzverse"
output:
  rmarkdown::html_vignette:
    keep_md: TRUE
tags:
- open data
- R
- Alzheimer's
author: Michael C. Donohue, Kedir Hussen, Oliver Langford, Richard Armenta, Gustavo Jimenez-Maggiora
authors:
- name: Michael C. Donohue
  orcid: 0000-0001-6026-2238
  affiliation: 1
- name: Kedir Hussen
  affiliation: 1
- name: Oliver Langford
  orcid: 0009-0006-8951-1326	
  affiliation: 1
- name: Richard Armenta
  affiliation: 1
- name: Gustavo Jimenez-Maggiora
  orcid: 0000-0001-9745-5121
  affiliation: 1
affiliations:
 - name: Alzheimer's Therapeutic Research Institute, University of Southern California
   index: 1
date: 7 August 2025
bibliography: references.bib
vignette: >
  %\VignetteIndexEntry{Welcome to the Alzverse}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", width = 68)
options(width = 68, cli.unicode = FALSE, cli.width = 68)
```

## Abstract

Sharing clinical research data is essential for advancing research in Alzheimer's disease (AD) and other therapeutic areas. However, challenges in data accessibility, standardization, documentation, usability, and reproducibility continue to impede this goal. In this article, we highlight the advantages of using `R` packages to overcome these challenges using two examples. The first example `R` package, 'A4LEARN' includes data from a randomized trial (the Anti-Amyloid Treatment in Asymptomatic Alzheimer’s [A4] study) and its companion observational study of biomarker negative individuals (the Longitudinal Evaluation of Amyloid Risk and Neurodegeneration [LEARN] study). The second example is the `ADNIMERGE2` `R` package, which includes data from the Alzheimer’s Disease Neuroimaging Initiative (ADNI). These packages bundle raw and processed data, documentation, and reproducible analyses into a portable, analysis-ready formats. By promoting collaboration, transparency, and reproducibility, `R` data packages can play a vital role in accelerating clinical research.

## Introduction

Alzheimer's disease (AD) is one of the leading neurodegenerative diseases worldwide, with growing evidence supporting its multifactorial etiology. The Alzheimer’s Disease Neuroimaging Initiative (ADNI) [@weiner2025overview] and similar projects have accumulated vast quantities of clinical, neuroimaging, and biomarker data, creating opportunities for scientific advances in the understanding and treatment of AD. ADNI has provided data for more than 6000 scientific papers publications [@weiner2025overview].

Availability of such data is on the rise, due in part to data sharing mandates from funders like the National Institutes of Health. However, it often takes considerable time and effort for researchers to gain sufficient familiarity with the data to produce meaningful analyses. Learning curves can be steep due to inadequate or hard-to-locate documentation and example analysis code.

Open-source software solutions, particularly in the form of `R` packages [@R-base; @wickham2023r], offer significant potential to address these barriers. The `R` programming language is widely used in biostatistics, machine learning, and clinical research. `R` packages are a well-known means for distributing cutting edge statistical software and documentation, and they often include data and analysis vignettes which demonstrate how the methods can be applied to data. But `R` packages can also be used to share data itself. The authors have maintained the ADNIMERGE `R` data package since 2017 [@ADNI2023]. ADNIMERGE has been cited by about 250 articles^[Based on a Google Scholar search of "ADNIMERGE" AND "package"] and has inspired related projects, such as the ANMERGE package of AddNeuroMed Consortium data [@birkenbihl2021anmerge]. @vuorre2021sharing demonstrated the utility of `R` packages for sharing data and analysis code from psychological experiments. 

We discuss how `R` packages can also facilitate easy access, harmonization, and analysis of larger clinical datasets from AD studies. These packages are built with the goal of providing an audit trail of derived data progeny, supporting reproducible research, and leveraging outstanding `R` tools for unit testing and validation [@testthat], websites [@pkgdown], and regulatory submissions [@pharmaverse2023]. 

In this paper we discuss the advantages of using `R` packages to share large clinical study datasets, and provide two new examples: the `A4LEARN` packages which includes data from a randomized trial (the Anti-Amyloid Treatment in Asymptomatic Alzheimer’s [A4] study) [@sperling2023trial] and its companion observational study of biomarker negative individuals (the Longitudinal Evaluation of Amyloid Risk and Neurodegeneration [LEARN] study) [@sperling2024amyloid]; and the `ADNIMERGE2` package, which includes latest data from the Alzheimer’s Disease Neuroimaging Initiative (ADNI) [@weiner2025overview].

## Advantages of R Data Packages

### Reproducibility, Portability and Documentation

The most important advantage of using `R` data packages for sharing clinical research data, is that it facilitates reproducible research. `R` is widely available and free to download [@R], commonly used in statistics courses, and has active development communities such as academic statisticians, pharmaceutical statisticians, and commercial enterprises such as Posit's RStudio Integrated Development Environment (IDE).

All `R` packages include a manual that details the functions and datasets in a standardized format. This content is linked `R` object's name accessible to the `R` user (e.g. by typing `?t.test`, or `?cars`) and can be browsed within the IDE. This is a drastic improvement compared to the typical case in which relevant data documentation might be contained in unlinked documents and/or data dictionary spreadsheets. `R` packages also typically provide analysis "vignettes", which demonstrate how functions can be applied to available datasets to produce analysis results as tables or figures. These are also linked and can be browsed within the IDE. Our `A4LEARN` package contains a vignette to exactly reproduce key findings of the published manuscript for the trial [@sperling2023trial]. This code can be used by outside researchers to jump start their own inquiries, and help ensure the data is being used correctly, efficiently, and consistent with the intentions of the study team.  

The `R` package bundle of data, `R` functions, documentation and vignettes is made portable as an efficiently compressed file which can be installed on any machine running `R`. Data files within the package are also efficiently compressed using R's `.RData` file format. These `.RData` files can be read by SPSS, Stata, and SAS [CONFIRM]. Another advantage to `.RData` compared to tabular text files (e.g. `.csv` files), is that they can utilize `R` object classes such as dates and factor variables, eliminating the need to process and annotate data prior to analysis.

The `pkgdown` `R` package [@pkgdown] makes it trivial to export documentation and vignettes as a website, and integrates well with code repositories such as GitHub. These `pkgdown` websites are searchable, and make the documentation and examples available to researchers who do not use `R`. See [atri-biostats.github.io/A4LEARN/](https://atri-biostats.github.io/A4LEARN) and [atri-biostats.github.io/ADNIMERGE2](https://github.com/atri-biostats/ADNIMERGE2) for examples.

### Standardized and Efficient Workflow and Testing

Questions often arise about the original source of data or how derived variables were defined. Therefore, it is crucial to preserve a record of data progeny. The standardize `R` package structure and build workflow makes it easy to retrace the steps of the package build. `R` packages also have a standardize framework for testing [@testthat] and tools for "assertive" programming to verify assumptions about the data [@assertr]. 

The R package structure and workflow has been well-documented [@wickham2023r]. We briefly review the structure while highlighting some key aspects in the context of the clinical research data.

**`data-raw`**. The `data-raw` directory is intended to house raw data and code to import and process raw data and store as `.Rdata` files in the `data` directory. Raw data can be preserved in the package with minimal manipulation, or it can be processed attaching meta data (variable labels and units), and ensuring factors and dates are stored as the correct object class. Data dictionary spreadsheets can be parsed to provide content for manual pages [@roxygen2].

**`vignettes`**. The `vignettes` directory houses the analysis demonstrations, typically as Rmarkdown (`.Rmd`) files [@rmarkdown]. We prefer to create derived datasets and variables as a vignette, as well, so that derivations are easily accessible to researchers within the IDE. These vignettes can include assertive programming to ensure data conforms to expectations [@assertr]. `ADNIMERGE2` contains vignettes which use [PHARMERVERSE](https://pharmaverse.org/) workflows to derive CDISC ADaM datasets.

**`R`**. The `R` directory contains `.R` files with code defining `R` functions and manual content [@roxygen2]. This directory can store scoring functions, which might be necessary to derive scores from item-level data from psychometric assessments, for example.

**`testthat`**. The `testthat` directory includes automated tests that are checked when the package is built. Sensitive and crucial code that requires replication by independent programmers can be tested here, to ensure they produce equivalent results on the actual data and/or test data.

**`reports`**. Report code that is not wanted as a vignette can be stored in a separate directory for general reports. Of note, `rmarkdown` supports "parameterized reports", which can produce different output depending on the supplied parameter(s). Clinical trials like A4 often include several outcomes collected on the same schedule and analyzed with the same approach. Instead of writing identical code for several outcomes, one generic parameterized rmarkdown file can produce all of these reports. Clinical trial outcomes are often aggregated into one long dataset with a row for each subject, time point, and outcome (see `ADQS` in the `A4LEARN` package). The parameterized report can filter this long dataset for the desired outcome and analyze only that outcome. Futhermore, using `R` parallel programming tools (e.g. @multidplyr), these reports can be produced in parallel. In the case of the A4 trial read out, once data from the blinded phase was locked and unblinded it only took about 30 minutes to build the final data package and render all planned analysis reports and summary slide decks!

## Example `R` Data Packages

### ADNIMERGE2

ADNIMERGE2 revamped to use pharmaverse tools and include ANDI4

### A4LEARN

A4LEARN demo code to reproduce primary trial results

Data sharing platforms

## Discussion

The development of `A4LEARN` and `ADNIMERGE2` represents a step forward in enabling the Alzheimer's disease research community to share and analyze data more effectively, and serve as an example . These packages facilitate the transition from proprietary software like SAS to open-source tools, allowing greater flexibility and transparency in the research process. The shift from SAS to `R` represents a broader trend in the clinical research community toward open-source and reproducible research practices.

While the packages have been validated and adopted by several researchers, challenges remain, particularly in the area of data security. The use of locally installed packages poses potential risks, which can be mitigated by using containerization and package management tools like Docker and renv for version control.

## Methods

We demonstrate The primary data sources for the packages are derived from the Alzheimer's Disease Neuroimaging Initiative (ADNI) and other studies, such as the A4 Study. These datasets include longitudinal clinical and neuroimaging data, cognitive test scores, genetic and biomarker data, and other modalities that have been harmonized to facilitate cross-study comparisons.
To ensure usability and consistency, we curated the datasets by mapping variables to standardized terminologies (e.g., CDISC ADaM, SDTM), handling missing data through imputation techniques, and deriving key analysis variables.
Package Development and Features
`A4LEARN` and `ADNIMERGE2` were developed using best practices in `R` package development, including:
•	R Package Architecture: Each package is modular, supporting various stages of data analysis, from raw data processing to the generation of regulatory-compliant datasets.
•	Data Standardization: The packages support standardization of clinical data, with built-in functions to harmonize variable formats, handle missing values, and generate standardized metadata.
•	Reproducibility: Built-in vignettes and examples guide users through the installation, data loading, and analysis processes. The packages integrate with tools like renv and Docker to facilitate reproducibility in different computing environments.
Implementation of Standardized Data Models
The `R` packages facilitate the creation of Analysis Data Model (ADaM) datasets, which are the gold standard for statistical analysis in clinical trials. The admiral package is used to generate ADaM datasets, and chevron, xlistings, and xtables are utilized to create regulatory-compliant TLGs. These tools ensure that the datasets conform to the standards required for regulatory submissions (e.g., FDA, EMA).

## Data Availability

Data is available from:

*	`A4LEARN`: [A4StudyData.org](A4StudyData.org)
*	`ADNIMERGE2`: [loni.usc.edu](loni.usc.edu)

Data documentation is available from 

*	`A4LEARN`: [atri-biostats.github.io/A4LEARN/](https://atri-biostats.github.io/A4LEARN)
*	`ADNIMERGE2`: [atri-biostats.github.io/ADNIMERGE2](https://github.com/atri-biostats/ADNIMERGE2)

## Code Availability

The packages and data are available for download from the following repositories:

*	A4LEARN: [github.com/atri-biostats/A4LEARN](https://github.com/atri-biostats/A4LEARN)
*	ADNIMERGE2: [github.com/atri-biostats/ADNIMERGE2](https://github.com/atri-biostats/ADNIMERGE2)

## Author Contributions

## Competing Interests

## Acknowledgements

## References


